services:
  energymeter:
    image: daisaja/energymeter:latest
    ports:
      - "3030:3030"
    env_file:
      - .env
    volumes:
      - /volume1/docker/energymeter/data:/data
    restart: unless-stopped